// Code generated by go-bindata.
// sources:
// dict/ipadict.aa
// dict/ipadict.ab
// dict/ipadict.ac
// dict/ipadict.ad
// dict/ipadict.ae
// dict/ipadict.af
// dict/ipadict.ag
// dict/ipadict.ah
// dict/ipadict.ai
// dict/ipadict.aj
// dict/ipadict.ak
// dict/ipadict.al
// dict/ipadict.am
// dict/ipadict.an
// dict/ipadict.ao
// dict/ipadict.ap
// dict/ipadict.aq
// dict/ipadict.ar
// dict/ipadict.as
// dict/ipadict.at
// dict/ipadict.au
// dict/ipadict.av
// dict/ipadict.aw
// DO NOT EDIT!

package data

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"dict/ipadict.aa": dictIpadictAa,
	"dict/ipadict.ab": dictIpadictAb,
	"dict/ipadict.ac": dictIpadictAc,
	"dict/ipadict.ad": dictIpadictAd,
	"dict/ipadict.ae": dictIpadictAe,
	"dict/ipadict.af": dictIpadictAf,
	"dict/ipadict.ag": dictIpadictAg,
	"dict/ipadict.ah": dictIpadictAh,
	"dict/ipadict.ai": dictIpadictAi,
	"dict/ipadict.aj": dictIpadictAj,
	"dict/ipadict.ak": dictIpadictAk,
	"dict/ipadict.al": dictIpadictAl,
	"dict/ipadict.am": dictIpadictAm,
	"dict/ipadict.an": dictIpadictAn,
	"dict/ipadict.ao": dictIpadictAo,
	"dict/ipadict.ap": dictIpadictAp,
	"dict/ipadict.aq": dictIpadictAq,
	"dict/ipadict.ar": dictIpadictAr,
	"dict/ipadict.as": dictIpadictAs,
	"dict/ipadict.at": dictIpadictAt,
	"dict/ipadict.au": dictIpadictAu,
	"dict/ipadict.av": dictIpadictAv,
	"dict/ipadict.aw": dictIpadictAw,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"dict": &bintree{nil, map[string]*bintree{
		"ipadict.aa": &bintree{dictIpadictAa, map[string]*bintree{}},
		"ipadict.ab": &bintree{dictIpadictAb, map[string]*bintree{}},
		"ipadict.ac": &bintree{dictIpadictAc, map[string]*bintree{}},
		"ipadict.ad": &bintree{dictIpadictAd, map[string]*bintree{}},
		"ipadict.ae": &bintree{dictIpadictAe, map[string]*bintree{}},
		"ipadict.af": &bintree{dictIpadictAf, map[string]*bintree{}},
		"ipadict.ag": &bintree{dictIpadictAg, map[string]*bintree{}},
		"ipadict.ah": &bintree{dictIpadictAh, map[string]*bintree{}},
		"ipadict.ai": &bintree{dictIpadictAi, map[string]*bintree{}},
		"ipadict.aj": &bintree{dictIpadictAj, map[string]*bintree{}},
		"ipadict.ak": &bintree{dictIpadictAk, map[string]*bintree{}},
		"ipadict.al": &bintree{dictIpadictAl, map[string]*bintree{}},
		"ipadict.am": &bintree{dictIpadictAm, map[string]*bintree{}},
		"ipadict.an": &bintree{dictIpadictAn, map[string]*bintree{}},
		"ipadict.ao": &bintree{dictIpadictAo, map[string]*bintree{}},
		"ipadict.ap": &bintree{dictIpadictAp, map[string]*bintree{}},
		"ipadict.aq": &bintree{dictIpadictAq, map[string]*bintree{}},
		"ipadict.ar": &bintree{dictIpadictAr, map[string]*bintree{}},
		"ipadict.as": &bintree{dictIpadictAs, map[string]*bintree{}},
		"ipadict.at": &bintree{dictIpadictAt, map[string]*bintree{}},
		"ipadict.au": &bintree{dictIpadictAu, map[string]*bintree{}},
		"ipadict.av": &bintree{dictIpadictAv, map[string]*bintree{}},
		"ipadict.aw": &bintree{dictIpadictAw, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

